# Generated by Django 5.2.3 on 2025-08-27 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('electeurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElecteurAuth',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_identifiant_valid', models.BooleanField(default=False)),
                ('is_facial_valid', models.BooleanField(default=False)),
                ('is_valid', models.BooleanField(default=False)),
                ('date_auth', models.DateTimeField(auto_now_add=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('otp_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('electeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_sessions', to='electeurs.electeur')),
            ],
            options={
                'indexes': [models.Index(fields=['electeur'], name='electeur_au_electeu_1a18e3_idx'), models.Index(fields=['is_valid'], name='electeur_au_is_vali_3a3508_idx'), models.Index(fields=['date_auth'], name='electeur_au_date_au_cc0f59_idx'), models.Index(fields=['expired_at'], name='electeur_au_expired_9dde6d_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('is_valid', False), models.Q(('is_identifiant_valid', True), ('is_facial_valid', True)), _connector='OR'), name='valid_requires_ident_and_face'), models.CheckConstraint(condition=models.Q(('is_facial_valid', False), ('is_identifiant_valid', True), _connector='OR'), name='face_requires_ident')],
            },
        ),
    ]
