# Generated by Django 5.2.3 on 2025-08-27 17:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('electeurs', '0001_initial'),
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id_resultat', models.AutoField(primary_key=True, serialize=False)),
                ('tour', models.PositiveIntegerField()),
                ('nb_votes', models.PositiveIntegerField(default=0)),
                ('total_votes_election', models.PositiveIntegerField(default=0)),
                ('taux_participation', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='elections.candidat')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='elections.election')),
            ],
        ),
        migrations.CreateModel(
            name='ResultatFinale',
            fields=[
                ('id_resultatFinale', models.AutoField(primary_key=True, serialize=False)),
                ('nb_vote_total_obtenu', models.PositiveIntegerField(default=0)),
                ('taux_participation', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('tour_finale', models.PositiveIntegerField(default=1)),
                ('date_finalisation', models.DateTimeField(default=django.utils.timezone.now)),
                ('archive_pdf', models.FileField(blank=True, null=True, upload_to='archives_resultats/')),
                ('candidat_elu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='victoires', to='elections.candidat')),
                ('election', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultat_final', to='elections.election')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id_vote', models.AutoField(primary_key=True, serialize=False)),
                ('tour', models.PositiveIntegerField(editable=False)),
                ('date_vote', models.DateTimeField(auto_now_add=True)),
                ('encrypted_candidat', models.TextField(editable=False)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='elections.candidat')),
                ('electeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='electeurs.electeur')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='elections.election')),
            ],
            options={
                'unique_together': {('election', 'electeur', 'tour')},
            },
        ),
    ]
