# Generated by Django 5.2.3 on 2025-08-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultatfinale',
            name='is_publish',
            field=models.BooleanField(default=False),
        ),
    ]
