# Generated by Django 5.2.3 on 2025-08-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electeurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='electeur',
            name='is_apte_vote',
            field=models.BooleanField(default=False),
        ),
    ]
